name: "unit tests"

on:
  push:
  pull_request:

jobs:
  build:
    name: build (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: GCC
            cc: gcc
            cxx: g++
          - name: Clang
            cc: clang
            cxx: clang++
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    steps:
    - name: checkout adt
      uses: actions/checkout@v4
      with:
        repository: cogu/adt
        ref: v0.3.7
        path: adt

    - name: checkout cutil
      uses: actions/checkout@v4
      with:
        repository: cogu/cutil
        path: cutil

    - name: checkout dtl_type
      uses: actions/checkout@v4
      with:
        path: main

    - name: configure
      run: cmake -S . -B build -DUNIT_TEST=ON
      working-directory: main

    - name: build
      run: cmake --build build --target dtl_type_unit
      working-directory: main

    - name: test
      run: ctest --test-dir build --output-on-failure
      working-directory: main
